### PR TITLE
Add Dokku instructions

### PR DESCRIPTION
**Pull request by ojosdegris**

### CODE REVIEW

**Comment by MichaelJCole** [comment]
Hey, this is good info.  How do you upload settings.json?  

I'm trying this out: https://github.com/JarnoLeConte/dokku-meteor

**Comment by ojosdegris** [comment]
@MichaelJCole  just added it to git.

**Comment by MichaelJCole** [comment]
Hey vittore, I didn't see anything about meteor settings.  Was there
another part to the PR?  I was fussing around with Docker and Dokku before
going back to Mupx.  For performance reasons, it's easier to do the build
on my machine.

Before going back, I didn't get all the way on the settings file.  I
learned Meteor loads settings from METEOR_SETTINGS environment variable or
from the file if specified, but I didn't finish.

Anyways, thanks for the buildpack!


On Sat, May 28, 2016 at 12:09 PM, vittore <notifications@github.com> wrote:

> @MichaelJCole <https://github.com/MichaelJCole> just added it to git.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/AdmitHub/meteor-buildpack-horse/pull/104#issuecomment-222319045>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABb2Fr-0qBIuPLd9zLwNF_DfCwzrFrp4ks5qGHbagaJpZM4IkKCC>
> .
>



-- 
Michael Cole
Founder and Engineer
https://bigSmall.io

**Comment by yourcelf** [comment]
Thanks for these instructions. Rather than clutter up the README further, I've added a [wiki page](https://github.com/AdmitHub/meteor-buildpack-horse/wiki/Dokku) for usage with Dokku based on your list here, and referenced it from the README.  Would love any further edits and improvements to these instructions there, including discussion of the role of dokku-meteor etc.

**Comment by MichaelJCole** [comment]
Nice choice!

On Mon, May 30, 2016 at 12:34 PM, Charlie DeTar <notifications@github.com>
wrote:

> Thanks for these instructions. Rather than clutter up the README further,
> I've added a wiki page
> <https://github.com/AdmitHub/meteor-buildpack-horse/wiki/Dokku> for usage
> with Dokku based on your list here, and referenced it from the README.
> Would love any further edits and improvements to these instructions there,
> including discussion of the role of dokku-meteor etc.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/AdmitHub/meteor-buildpack-horse/pull/104#issuecomment-222532093>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABb2FvsUGu5ParjaVPN3lsbKKR6zYVjRks5qGx-mgaJpZM4IkKCC>
> .
>



-- 
Michael Cole
Founder and Engineer
https://bigSmall.io

**Comment by MichaelJCole** [comment]
Hey guys, I updated the wiki with what I learned.  Feel free to edit,
wiki-style :-)

On Mon, May 30, 2016 at 12:40 PM, Michael Cole <michael@bigsmall.io> wrote:

> Nice choice!
>
> On Mon, May 30, 2016 at 12:34 PM, Charlie DeTar <notifications@github.com>
> wrote:
>
>> Thanks for these instructions. Rather than clutter up the README further,
>> I've added a wiki page
>> <https://github.com/AdmitHub/meteor-buildpack-horse/wiki/Dokku> for
>> usage with Dokku based on your list here, and referenced it from the
>> README. Would love any further edits and improvements to these instructions
>> there, including discussion of the role of dokku-meteor etc.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/AdmitHub/meteor-buildpack-horse/pull/104#issuecomment-222532093>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ABb2FvsUGu5ParjaVPN3lsbKKR6zYVjRks5qGx-mgaJpZM4IkKCC>
>> .
>>
>
>
>
> --
> Michael Cole
> Founder and Engineer
> https://bigSmall.io
>



-- 
Michael Cole
Founder and Engineer
https://bigSmall.io

**Comment by ojosdegris** [comment]
Hi guys,

I updated wiki page with instructions for `METEOR_SETTINGS`. Basically same thing stands as with `ROOT_URL`. You have to use `dokku config:set`

**Pull request closed without merging**
