### PR TITLE
File not found until restart for meteor bootstrap sass

### PR DESCRIPTION
**Pull request by dalloro**
Reopening the PR, after the move to the new branch on the hosting fork.

### CODE REVIEW

**Comment by yourcelf** [comment]
Sorry for the delay in merging this.

**Comment by reywood** [comment]
Hi. I ran across this thread and the thread in PR #15 while looking into a different problem, but I think I may have a better solution than waiting 60 seconds for Meteor to startup and build the requisite files before killing it with the `timeout` command. If you run meteor with the `--test` param (as in `meteor run --test`), it will exit on its own after the `file to import not found or unreadable` error occurs while still building out the `.meteor/local/build/...` files that are needed for the subsequent `meteor build ...` call. Something you might want to try out.

**Comment by yourcelf** [comment]
@reywood, wouldn't that execute tests, though?  Seems like that could be a problem, as tests could include selenium browser dependencies and other big gnarly stuff that wouldn't be in the heroku.

**Comment by reywood** [comment]
Well, as long as `.meteor/local` doesn't exist when `meteor run --test` is executed, it should just fail without running tests.

**Comment by yourcelf** [comment]
But meteor will create ``.meteor/local`` on first run of ``meteor run --test``.  If there's no problem creating .meteor/local, it *does* run potentially heavy tests, and the process never exits.  I could be missing something, but I don't think this gets us any further -- we'd still need a timeout to kill the process in case it doesn't fail on its own.

**Comment by reywood** [comment]
I guess my assumption was that someone would only set `BUILDPACK_PRELAUNCH_METEOR` if assets needed to be copied to `.meteor/local` in which case it would always fail the first time. I admit I'm not familiar with meteor-buildpack-horse, so I may be missing something.

**Pull request merged**
