### PR TITLE
Added support for app projects created with the Iron scaffolding tool

### PR DESCRIPTION
**Pull request by lirbank**
The Iron scaffolding tool place the Meteor app in /app/ instead of in the root, so I've added so Horse try /app/ if a Meteor app can't be found in the root.

### CODE REVIEW

**Comment by lirbank** [comment]
@yourcelf - Any chance you could merge this PR?

**Comment by yourcelf** [comment]
Hey!  Thanks for the PR.  I'm interested in keeping things simple, and not having too many edge cases and conditions that might go out of date as tools evolve.  For the most part, I'd like to keep this build pack focused on vanilla meteor, and let branches or forks handle edge cases for particular configurations.

I hadn't heard of the Iron scaffolding tool before, and you're the first to have requested support for it.  Do you think it's something that is widely used enough that you think people need this to be supported in master here?  Or might it be something that would better exist in a specific branch or fork for that?

**Comment by lirbank** [comment]
Heya! I'm a contributor to Iron and we've just recently changed the project structure (not released yet) which moves meteor to /app/ instead of having it in the root. So I realized this will screw it up for the heroku build packs, and since I've been using Horse for some time I suggested we contribute to it instead of writing our own Iron build pack.

I totally understand if you decide to not merge but it would be totally cool if you did. Iron is the only scaffolding tool that I know of for meteor. The lead developer of Iron is @cmatter who also wrote the Iron Router for meteor so it has good support.

**Comment by lirbank** [comment]
I mean @cmather :)

**Comment by lirbank** [comment]
Hi @yourcelf - just wanted to check in on this. Are you okay with merging? Anything you need from me?

**Comment by yourcelf** [comment]
Sorry for delay.

**Comment by lirbank** [comment]
Awesome, thanks!

**Pull request merged**
